# Generated by Django 3.0.8 on 2020-08-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='captions',
            new_name='caption',
        ),
    ]
