# Generated by Django 3.0.8 on 2020-08-06 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20200805_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
